
#AoA server-side configuration options
["General Settings"]
	#Set to false to stop non-player entities from using the AoA portal system.
	allowNonPlayerPortalTravel = true
	#Configure the maximum amount of minions a player can have at a given time
	#Range: 1 ~ 200
	maxMinions = 10
	#Set this to false to disable enchantments that breach level caps
	allowUnsafeInfusion = true
	#Modifier for global xp gain for all players for AoA skills.
	#Higher numbers means more xp gained
	#Range: 0.0 ~ 1000.0
	globalXpModifier = 1.0
	#Adjust this value to modify how far to look for safe/existing portal locations.
	#The lower the value, the faster it runs
	#Range: 1 ~ 128
	portalSearchRadius = 24
	#Set this to true to make Corrupted Travellers easier to find, causing them to glow through blocks when nearby.
	easyCorruptedTravellers = false
	#Set to false to stop AoA saving loot-drops from explosions.
	saveLootFromExplosions = true

