:: Start script generated by ServerPackCreator.
:: This script checks for the Minecraft and Forge JAR-files, and if they are not found, they are downloaded and installed.
:: If everything is in order, the server is started.
@ECHO off
SetLocal EnableDelayedExpansion

SET MINECRAFT="1.16.5"
SET FORGE="36.2.34"
SET ARGS=

IF NOT EXIST forge.jar (

  ECHO Forge Server JAR-file not found. Downloading installer...
  powershell -Command "(New-Object Net.WebClient).DownloadFile('https://files.minecraftforge.net/maven/net/minecraftforge/forge/%MINECRAFT%-%FORGE%/forge-%MINECRAFT%-%FORGE%-installer.jar', 'forge-installer.jar')"

  IF EXIST forge-installer.jar (

    ECHO Installer downloaded. Installing...
    java -jar forge-installer.jar --installServer
    MOVE forge-%MINECRAFT%-%FORGE%.jar forge.jar

    IF EXIST forge.jar (
      DEL forge-installer.jar
      ECHO Installation complete. forge-installer.jar deleted.
    )

  ) ELSE (
    ECHO forge-installer.jar not found. Maybe the Forges servers are having trouble.
    ECHO Please try again in a couple of minutes.
  )
) ELSE (
  ECHO forge.jar present. Moving on...
)

IF NOT EXIST minecraft_server.%MINECRAFT%.jar (
  ECHO Minecraft Server JAR-file not found. Downloading...
  powershell -Command "(New-Object Net.WebClient).DownloadFile('https://launcher.mojang.com/v1/objects/1b557e7b033b583cd9f66746b7a9ab1ec1673ced/server.jar', 'minecraft_server.%MINECRAFT%.jar')"
) ELSE (
  ECHO minecraft_server.%MINECRAFT%.jar present. Moving on...
)

IF NOT EXIST eula.txt (
  ECHO Mojang's EULA has not yet been accepted. In order to run a Minecraft server, you must accept Mojang's EULA.
  ECHO Type "I agree" to indicate that you agree to Mojang's EULA.
  ECHO Mojang's EULA is available to read at https://account.mojang.com/documents/minecraft_eula
  ECHO Do you agree to Mojang's EULA?
  set /P "Response="
  set agree=I agree
  IF !Response! == !agree! (
    ECHO User agreed to Mojang's EULA.
    ECHO #By changing the setting below to TRUE you are indicating your agreement to our EULA ^(https://account.mojang.com/documents/minecraft_eula^).> eula.txt
    ECHO eula=true>> eula.txt
  ) else (
    ECHO User did not agree to Mojang's EULA. 
  )
) ELSE (
  ECHO eula.txt present. Moving on...
)

ECHO Starting server...
ECHO Minecraft version: %MINECRAFT%
ECHO Forge version: %FORGE%
ECHO Java args: %ARGS%

"C:\Program Files\Eclipse Adoptium\jdk-8.0.382.5-hotspot\bin\java" %ARGS% -jar forge.jar nogui

PAUSE